### ISSUE TITLE
Problem while deploying the connector via Helm chart

### ISSUE THREAD

**Issue by mjbernal** [FIWARE-Ops/data-space-connector#31]
Hello!

I'm following the instructions to deploy the connector using Helm:
`# add the repo`
`helm repo add dsc https://fiware-ops.github.io/data-space-connector/`
`# install the chart`
`helm install dsc/data-space-connector`

When running **_helm install dsc-test dsc/data-space-connector_**, i get the following error:

`Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Application "demo-mysql" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "dsc-test": current value is "data-space-connector-1695806028"`

Then I tried to run it with the name **_data-space-connector-1695806028_** (**_helm install data-space-connector-1695806028 dsc/data-space-connector_** ) , but I get the following error:

`Error: INSTALLATION FAILED: failed to create resource: Service "data-space-connector-1695806028-tm-forum-api-customer-bill-management" is invalid: metadata.name: Invalid value: "data-space-connector-1695806028-tm-forum-api-customer-bill-management": must be no more than 63 characters`

**Comment by ScorpioBroker** [comment]
Hi,

same issue here. Manual uninstall and then installing it with helm install dsc-test dsc/data-space-connector again helped to get passed this error. However this just got me to the next error 

`client.go:310: [debug] Starting delete for "dataspaceconnector-keycloak-keycloak-config-cli" Job
client.go:128: [debug] creating 1 resource(s)
client.go:540: [debug] Watching for changes to Job dataspaceconnector-keycloak-keycloak-config-cli with timeout of 5m0s
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: ADDED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 0, jobs failed: 1, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
client.go:607: [debug] dataspaceconnector-keycloak-keycloak-config-cli: Jobs active: 0, jobs failed: 1, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for dataspaceconnector-keycloak-keycloak-config-cli: MODIFIED
Error: INSTALLATION FAILED: failed post-install: job failed: BackoffLimitExceeded
helm.go:84: [debug] failed post-install: job failed: BackoffLimitExceeded
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.4.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598
`

**Comment by dwendland** [comment]
Hi,

did you provide any configuration parameters?
You definitely need to provide values for the deployment according to your environment, DNS/Ingress, VC types, etc, and also data space infrastructure (e.g., address of the trust anchor). 

The repo provides an example Helm values file for Helm deployments for a fictitious service provider: https://github.com/FIWARE-Ops/data-space-connector/tree/main/examples/service-provider-ips
Please have a look. Basically this contains all the config parameters, that need to be provided for a running setup.

**Comment by dwendland** [comment]
Closed due to inactivity here. Also we had some meetings to clarify the deployment.
