### ISSUE TITLE
Local deployment under examples?

### ISSUE THREAD

**Issue by gboege** [FIWARE-Ops/data-space-connector#75]
The local deployment is mentioned and linked in the text. 
Would it be helpful to also add a link, text or folder to the examples folder, too?
For consitency reasons?

**Comment by dwendland** [comment]
Do you mean this link?
https://github.com/FIWARE-Ops/data-space-connector?tab=readme-ov-file#examples

**Comment by gboege** [comment]
The link to local depolyment here: 
https://github.com/FIWARE-Ops/data-space-connector?tab=readme-ov-file#deployment

**Comment by dwendland** [comment]
So what is missing?

**Comment by gboege** [comment]
Actually my last comment was incorrect. So yes, I meant the examples folder.

**Comment by dwendland** [comment]
But that's already linked in the section I mentioned

**Comment by gboege** [comment]
ok, true. not my best comment ever. will close it.
